// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGDSFkFCMNGKoVvo_PNpNm1SGVmzrcetM',
    appId: '1:866517428193:web:4dcf3b18593b99bc86d4a0',
    messagingSenderId: '866517428193',
    projectId: 'vantureapp-36653',
    authDomain: 'vantureapp-36653.firebaseapp.com',
    storageBucket: 'vantureapp-36653.firebasestorage.app',
    measurementId: 'G-85156CDNC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYQkI3Pl03YjLowI9tlZZp7772n8EmLDA',
    appId: '1:866517428193:android:53028ed16d7f226386d4a0',
    messagingSenderId: '866517428193',
    projectId: 'vantureapp-36653',
    storageBucket: 'vantureapp-36653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByfhDV-J0USwa01zJAEufB9oq_culRo7c',
    appId: '1:866517428193:ios:2ca0ae47f4df66e186d4a0',
    messagingSenderId: '866517428193',
    projectId: 'vantureapp-36653',
    storageBucket: 'vantureapp-36653.firebasestorage.app',
    androidClientId: '866517428193-olu0fou6391elvgq05rf3215negi17r6.apps.googleusercontent.com',
    iosClientId: '866517428193-1dq563bo1udrdi0ag3v0oham0p1mh4dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRentalApp',
  );
}
